### ISSUE TITLE
Notifications are not buffered?

### ISSUE THREAD

**Issue by caspervonb** [buggerjs/bugger#56]
It seems that notifications are not buffered like they are in chromium based implementations.

Here's a small example, I'll leave out the code as it isn't that relevant, rather I'll dump the request/response data from `node-rdbg`.

```
TAP version 13
# spawn
stdout: 'chrome-devtools://devtools/bundled/inspector.html?ws=127.0.0.1:4000/websocket'
stdout: 'console log'
RDBG 38874: connect
RDBG 38874: request { id: 0, method: 'Console.enable', params: {} }
RDBG 38874: message { method: 'Debugger.scriptParsed',
  params: 
   { scriptId: '236',
     url: 'file:///usr/local/lib/node_modules/bugger/lib/agents/console/index.js',
     lineCount: 103,
     sourceOffset: { line: 0, column: 0 },
     context: null,
     evalContext: null } }
RDBG 38874: response { id: 0, method: 'Console.enable', params: {} }, { id: 0, error: null }
```

So there are two things going "wrong" here. Or they are at-least behaving differently from the spec.

- I have not called  `Debugger.enable`, yet I am getting `scriptParsed` notifications.
- I am not getting `Console.messageAdded` notifications for the console messages that occurred before `Console.enable` is called.

**Comment by jkrems** [comment]
I *think* this would need to happen on a case-by-case basis. E.g. when reloading or reconnecting, the agent instances are actually reused right now. So it would be a big(ish) change to make them actually track if the current client called `enable` already.

* Keeping a complete memory of the console output until `clear` was called sounds good
* It would be possible to silence `scriptParsed` until the first client connects. But I'm not sure if that's worth it since reconnecting will revert back to the current behavior. It's save to ignore `scriptParsed` before `enable` though since `enable` will trigger a send of all scripts known so far anyhow.

**Comment by jkrems** [comment]
https://github.com/buggerjs/bugger/pull/60 should address the `Console.messageAdded` case. For `scriptParsed` it would potentially be possible to track the `enable` state for all agents and stop them from emitting anything if they are not enabled. But I'd honestly prefer to just depend on clients to work the same way that Chrome does (ignore/drop messages received before `enable` was called). It's hard enough to track what Chrome is doing (especially since that changes every couple of weeks).
